version: '2'
services:
    pondnotes-app:
        image: pondnotes
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://pondnotes-mariadb:3306/pondnotes
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=pondnotes-elasticsearch:9300
        ports:
            - 8085:8085
    pondnotes-mariadb:
        extends:
            file: mariadb.yml
            service: pondnotes-mariadb
    pondnotes-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: pondnotes-elasticsearch
